name: Continuous Integration

on:
  push:
    branches:
#      - main
      - ci-cd-test-branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: echo "Tests passed successfully!"

    - name: Create CI success artifact
      run: touch ci-success.txt

    - name: Upload CI success artifact
      uses: actions/upload-artifact@v2
      with:
        name: ci-artifact
        path: ci-success.txt
